### ISSUE TITLE
Preferences and Guide Editor Pop Up raise error

### ISSUE THREAD

**Issue by ddaanniiieeelll** [typesupply/guidetool#15]
Hello,

the tool works great until I either want to access the Preferences or I try to open the guide editor.
Trying to open the preferences raises this error:

```
Traceback (most recent call last):
  File "menu_showPrefs.py", line 4, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 51, in OpenWindow
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/controllers.py", line 37, in __init__
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/defaults.py", line 298, in build
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/tools/builder.py", line 72, in makeItem
TypeError: __init__() got an unexpected keyword argument 'contentDescription'
```

Trying to open the Guide Editor this one:
```
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/tool.py", line 537, in keyDown
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/tool.py", line 265, in openGuidelineEditor
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/controllers.py", line 37, in __init__
  File "/Users/daniel/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/editor.py", line 223, in build
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/tools/builder.py", line 72, in makeItem
TypeError: __init__() got an unexpected keyword argument 'contentDescription'
```

I’m currently using 
RF Version 4.2 (build 2204191146)
Guide Tool 1.1 from Mechanic
on a
M1 Mac with OS Monterey 12.0.1

Tried with the install from Mechanic and downloaded directly from the repo :(

**Comment by typesupply** [comment]
This will be fixed soon. I made some changes in ezui and this tool needed to be updated.

**Comment by typesupply** [comment]
This should be fixed in the version I just released. There may be other issues because of ezui changes between RoboFont 4.2 and the in-development 4.3.
