### ISSUE TITLE
Typing coordinates into guideline popup results in fontParts traceback

### ISSUE THREAD

**Issue by colinmford** [typesupply/guidetool#21]
Reproduce:
1. Drag in guide from side
2. Double click on it to bring up guide detail editor
3. Edit position field

Gets traceback:
```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
    self.action_(notification.object())
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 507, in action_
    self.callback(sender)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/items.py", line 2112, in _internalCallback
    self._callback(self)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/containers.py", line 574, in _containerCallback
    self._externalCallback(self)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/ezui/containers.py", line 1893, in _containerCallback
    self._externalCallback(self)
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/editorView.py", line 203, in internalCallback
    guideline.x = x
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/fontParts/base/base.py", line 101, in __set__
    setter(value)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/fontParts/base/guideline.py", line 138, in _set_base_x
    value = normalizers.normalizeX(value)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 803, in normalizeX
    % type(value).__name__)
TypeError: X coordinates must be instances of :ref:`type-int-float`, not pyobjc_unicode.
```

I imagine lines [203-205](https://github.com/typesupply/guidetool/blob/dcdbed6167d899901c085ff491c786c08834f2c9/build/Guide%20Tool.roboFontExt/lib/guideTool/editorView.py#L203) need to be cast as floats

**Comment by typesupply** [comment]
I'm not sure why this is happening. ezui is supposed to handle the conversion and I can't reproduce it here. I added a safety conversion function that will hopefully make triple sure this doesn't happen anymore. Please let me know if it persists.
