### ISSUE TITLE
EZUI error in Robofont 4.4b

### ISSUE THREAD

**Issue by colinmford** [typesupply/guidetool#25]
Hey @typesupply,

I'm getting the following traceback in the RF4.4b when double clicking on a guide using the guide tool:

```
Traceback (most recent call last):
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/tool.py", line 298, in mouseDown
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/tool.py", line 268, in openGuidelineEditor
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/controllers.py", line 34, in __init__
  File "/Users/colinmford/Library/Application Support/RoboFont/plugins/Guide Tool.roboFontExt/lib/guideTool/editor.py", line 63, in build
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/windows/popUp.py", line 171, in __init__
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/windows/base.py", line 75, in _initAdditions
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/windows/base.py", line 211, in setContent
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/tools/builder.py", line 80, in makeItem
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/ezui/tools/builder.py", line 128, in instantiateItem
ezui.errors.EZUIError: 

Unknown key(s) in item description.

File Name:
/Applications/RoboFont.app/Contents/Resources/__boot__.py

Item Type:
GuideToolGuidelineEditor

Item Identifier:
content

Unknown Key/Value Pairs:
- contents : []

Allowed Keys:
- callback
- container
- controller
- descriptionData
- identifier
- onlyFontLevel
```

Definitely looks like something changed in EZUI, you probably know exactly what it is, so instead of fumbling around with a PR I'm just gonna leave this in your hands :)

Here's my RF info:
```
RoboFont 4.4b (build 2303080915)
Python 3.9.13
MacOS 13.2.1 (Darwin 22.3.0)
Processor i386 (x86_64)
```

**Comment by typesupply** [comment]
Thanks! I just pushed a new version.

I was using my own tools as test cases while I was developing the ezui API, so some things need to be updated to the final API.
